## model configuration
model: htcdc
backbone: efficientnetb0
project: HTCDC

## data configuration
batch_size: 32
num_workers: 8 

## training configuration
max_epochs: 500 
lr: 0.0001
chamfer_weight: 0.01
log_interval: 50

optimizer: AdamW

early_stopping: ['mae', 'rmse', 'val/loss_total']
early_stopping_mode: ['min', 'min', 'min'] 
